const NAME_OR_PASSWORD_IS_REQUIRED ='name_or_password_is_required';
const USER_NOT_EXISTS = 'user_already_exists';
const USER_IS_EXISTS = 'user_is_exists';
const PASSWORD_IS_INCORRENT = 'password_is_incorrent'
const UNAUTHORIZATION = 'UNAUTHORIZATION'
const UNPROMISSION = 'UNPROMISSION'

module.exports = {
    NAME_OR_PASSWORD_IS_REQUIRED,USER_NOT_EXISTS,USER_IS_EXISTS,PASSWORD_IS_INCORRENT,
    UNAUTHORIZATION,UNPROMISSION
}